version: '3'

services:
   multivac_server:
     image: multivac_server:v1
     restart: always
     ports:
       - "5000:5000"

   multivac_worker:
     image: multivac_worker:v1
     restart: always
     ports:
       - "5001:5001"

   multivac_redis:
     image: redis:latest
     restart: always
     ports:
       - "6379:6379"

   multivac_mongo:
     image: multivac_mongo:v1
     ports:
       - "27017:27017"

networks:
   unbabel_network:
