version: '3'

services:
   multivac-server:
     build:
        context: ./server
        dockerfile: Dockerfile 
     image: multivac-server:v1
     restart: always
     ports:
       - "5000:5000"
     networks:
       - unbabel_network

   multivac-worker:
     build:
        context: ./worker
        dockerfile: Dockerfile
     image: multivac-worker:v1
     restart: always
     networks:
       - unbabel_network

   multivac-redis:
     image: redis:4.0
     restart: always
     ports:
       - "6379:6379"
     networks:
       - unbabel_network

   multivac-mongo:
     build:
        context: ./mongodb
        dockerfile: Dockerfile
     image: multivac-mongo:v1
     ports:
       - "27017:27017"
     networks:
       - unbabel_network

networks:
  unbabel_network:
